#!/bin/bash
# IPv6 Configuration Helper Script
# Assists with common IPv6 configuration tasks

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        print_error "This operation requires root privileges"
        exit 1
    fi
}

# Enable IPv6
enable_ipv6() {
    check_root
    print_info "Enabling IPv6..."

    # Via sysctl
    sysctl -w net.ipv6.conf.all.disable_ipv6=0
    sysctl -w net.ipv6.conf.default.disable_ipv6=0

    # Load module if needed
    modprobe ipv6 2>/dev/null || true

    print_success "IPv6 enabled"
}

# Disable IPv6
disable_ipv6() {
    check_root
    print_warning "Disabling IPv6..."

    sysctl -w net.ipv6.conf.all.disable_ipv6=1
    sysctl -w net.ipv6.conf.default.disable_ipv6=1

    print_success "IPv6 disabled"
}

# Configure static IPv6 address
configure_static() {
    check_root

    local interface="$1"
    local address="$2"
    local prefix="$3"

    if [ -z "$interface" ] || [ -z "$address" ] || [ -z "$prefix" ]; then
        print_error "Usage: $0 static <interface> <address> <prefix>"
        exit 1
    fi

    print_info "Configuring static IPv6 address..."
    print_info "Interface: $interface"
    print_info "Address: $address/$prefix"

    ip -6 addr add "$address/$prefix" dev "$interface"
    ip link set "$interface" up

    print_success "Static address configured"
}

# Enable IPv6 forwarding
enable_forwarding() {
    check_root
    print_info "Enabling IPv6 forwarding..."

    sysctl -w net.ipv6.conf.all.forwarding=1

    print_success "IPv6 forwarding enabled"
    print_warning "Note: This may disable SLAAC on some interfaces"
}

# Disable IPv6 forwarding
disable_forwarding() {
    check_root
    print_info "Disabling IPv6 forwarding..."

    sysctl -w net.ipv6.conf.all.forwarding=0

    print_success "IPv6 forwarding disabled"
}

# Enable privacy extensions
enable_privacy() {
    check_root
    print_info "Enabling IPv6 privacy extensions..."

    # 2 = prefer temporary addresses
    sysctl -w net.ipv6.conf.all.use_tempaddr=2
    sysctl -w net.ipv6.conf.default.use_tempaddr=2

    print_success "Privacy extensions enabled (preferring temporary addresses)"
}

# Disable privacy extensions
disable_privacy() {
    check_root
    print_info "Disabling IPv6 privacy extensions..."

    sysctl -w net.ipv6.conf.all.use_tempaddr=0
    sysctl -w net.ipv6.conf.default.use_tempaddr=0

    print_success "Privacy extensions disabled"
}

# Enable SLAAC
enable_slaac() {
    check_root
    print_info "Enabling SLAAC (Stateless Address Autoconfiguration)..."

    sysctl -w net.ipv6.conf.all.autoconf=1
    sysctl -w net.ipv6.conf.all.accept_ra=1

    print_success "SLAAC enabled"
}

# Disable SLAAC
disable_slaac() {
    check_root
    print_info "Disabling SLAAC..."

    sysctl -w net.ipv6.conf.all.autoconf=0
    sysctl -w net.ipv6.conf.all.accept_ra=0

    print_success "SLAAC disabled"
}

# Add route
add_route() {
    check_root

    local destination="$1"
    local gateway="$2"
    local interface="$3"

    if [ -z "$destination" ]; then
        print_error "Usage: $0 add-route <destination> [gateway] [interface]"
        exit 1
    fi

    print_info "Adding IPv6 route..."

    local cmd="ip -6 route add $destination"
    [ -n "$gateway" ] && cmd="$cmd via $gateway"
    [ -n "$interface" ] && cmd="$cmd dev $interface"

    eval "$cmd"

    print_success "Route added: $destination"
}

# Show current configuration
show_config() {
    print_info "Current IPv6 Configuration:"
    echo ""

    echo "IPv6 Status:"
    local disabled=$(sysctl -n net.ipv6.conf.all.disable_ipv6 2>/dev/null || echo "unknown")
    if [ "$disabled" = "0" ]; then
        echo "  ✓ IPv6 is ENABLED"
    else
        echo "  ✗ IPv6 is DISABLED"
    fi

    echo ""
    echo "Key Settings:"
    echo "  Forwarding: $(sysctl -n net.ipv6.conf.all.forwarding 2>/dev/null || echo 'N/A')"
    echo "  Autoconf (SLAAC): $(sysctl -n net.ipv6.conf.all.autoconf 2>/dev/null || echo 'N/A')"
    echo "  Accept RA: $(sysctl -n net.ipv6.conf.all.accept_ra 2>/dev/null || echo 'N/A')"
    echo "  Privacy Extensions: $(sysctl -n net.ipv6.conf.all.use_tempaddr 2>/dev/null || echo 'N/A')"

    echo ""
    echo "Addresses:"
    ip -6 addr show | grep "inet6" | sed 's/^/  /'
}

# Save configuration permanently
save_config() {
    check_root
    print_info "Saving configuration permanently..."

    local conf_file="/etc/sysctl.d/99-ipv6.conf"

    cat > "$conf_file" << EOF
# IPv6 Configuration
# Generated by ipv6-config.sh on $(date)

net.ipv6.conf.all.disable_ipv6 = $(sysctl -n net.ipv6.conf.all.disable_ipv6)
net.ipv6.conf.default.disable_ipv6 = $(sysctl -n net.ipv6.conf.default.disable_ipv6)
net.ipv6.conf.all.forwarding = $(sysctl -n net.ipv6.conf.all.forwarding)
net.ipv6.conf.all.autoconf = $(sysctl -n net.ipv6.conf.all.autoconf)
net.ipv6.conf.all.accept_ra = $(sysctl -n net.ipv6.conf.all.accept_ra)
net.ipv6.conf.all.use_tempaddr = $(sysctl -n net.ipv6.conf.all.use_tempaddr)
net.ipv6.conf.default.use_tempaddr = $(sysctl -n net.ipv6.conf.default.use_tempaddr)
EOF

    print_success "Configuration saved to $conf_file"
    print_info "Changes will persist after reboot"
}

# Show help
show_help() {
    cat << EOF
IPv6 Configuration Helper

Usage: $0 <command> [options]

Commands:
  enable              Enable IPv6
  disable             Disable IPv6

  static <iface> <addr> <prefix>
                      Configure static IPv6 address
                      Example: $0 static eth0 2001:db8::1 64

  enable-forwarding   Enable IPv6 forwarding (routing)
  disable-forwarding  Disable IPv6 forwarding

  enable-privacy      Enable privacy extensions
  disable-privacy     Disable privacy extensions

  enable-slaac        Enable SLAAC (autoconfiguration)
  disable-slaac       Disable SLAAC

  add-route <dest> [gateway] [iface]
                      Add IPv6 route
                      Example: $0 add-route 2001:db8::/32 2001:db8::1

  show                Show current configuration
  save                Save current configuration permanently

  help                Show this help message

Note: Most commands require root privileges

Examples:
  $0 enable
  $0 static eth0 2001:db8::10 64
  $0 enable-privacy
  $0 save
EOF
}

# Main
case "${1:-}" in
    enable)
        enable_ipv6
        ;;
    disable)
        disable_ipv6
        ;;
    static)
        configure_static "$2" "$3" "$4"
        ;;
    enable-forwarding)
        enable_forwarding
        ;;
    disable-forwarding)
        disable_forwarding
        ;;
    enable-privacy)
        enable_privacy
        ;;
    disable-privacy)
        disable_privacy
        ;;
    enable-slaac)
        enable_slaac
        ;;
    disable-slaac)
        disable_slaac
        ;;
    add-route)
        add_route "$2" "$3" "$4"
        ;;
    show)
        show_config
        ;;
    save)
        save_config
        ;;
    help|--help|-h|"")
        show_help
        ;;
    *)
        print_error "Unknown command: $1"
        echo "Run '$0 help' for usage information"
        exit 1
        ;;
esac
